version: '3.7'
services:
  db:
    image: mysql:8.0.30
    ports:
      - 3306:3306
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: username
      MYSQL_PASSWORD: password
volumes:
  dbdata:
